titles: 
  level0: !ruby/regexp '/^= +(?<title>[\S].*?)( +=)?$/'
  level1: !ruby/regexp '/^== +(?<title>[\S].*?)( +==)?$/'
  level2: !ruby/regexp '/^=== +(?<title>[\S].*?)( +===)?$/'
  level3: !ruby/regexp '/^==== +(?<title>[\S].*?)( +====)?$/'
  level4: !ruby/regexp '/^===== +(?<title>[\S].*?)( +=====)?$/'
  blocktitle: !ruby/regexp '/^\.(?<title>([^.\s].*)|(\.[^.\s].*))$/'